DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS movies CASCADE;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE movies (
	id BIGSERIAL PRIMARY KEY,
	user_id INT REFERENCES users(id),
	title VARCHAR NOT NULL,
	overview VARCHAR,
	release_date VARCHAR,
	voter_average VARCHAR,
	movie_id VARCHAR
);
